name    'gabriel-freeswitch'
version '0.1.0'
source 'https://github.com/gabrielbull/puppet-freeswitch'
author 'gabriel'
license 'MIT'
summary 'Setup Freeswitch'
description 'Puppet module for installing freeswitch'
project_page 'https://github.com/gabrielbull/puppet-freeswitch'
