name    'gabriel-freeswitch'
version '1.0.0'
source 'https://github.com/gabrielbull/puppet-freeswitch'
author 'gabriel'
license 'MIT'
summary 'Setup Freeswitch'
description 'Setup Freeswitch'
project_page 'https://github.com/gabrielbull/puppet-freeswitch'
